// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"angrymiao-go/app/service/main/user/internal/dao"
	"angrymiao-go/app/service/main/user/internal/server/grpc"
	"angrymiao-go/app/service/main/user/internal/server/http"
	"angrymiao-go/app/service/main/user/internal/server/rpc"
	"angrymiao-go/app/service/main/user/internal/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	redisClient, err := dao.NewRedisClient()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := dao.NewDB()
	if err != nil {
		return nil, nil, err
	}
	daoDao, cleanup2, err := dao.New(redisClient, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serviceService, cleanup3, err := service.New(daoDao)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	engine, err := http.New(serviceService)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server, err := grpc.New(serviceService)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rpcServer := rpc.New(serviceService)
	app, cleanup4, err := NewApp(serviceService, engine, server, rpcServer)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
