[Server]
    addr = "0.0.0.0:8000"
    timeout = "1s"
[db]
    dsn = "root:123456@tcp(127.0.0.1:3306)/punk-canal?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4&allowNativePasswords=True"
    active = 5
    idle = 2
    idleTimeout = 240
    queryTimeout = 1
    execTimeout = 1
    tranTimeout = 1