// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dao

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func newTestDao() (*Dao, func(), error) {
	redisClient, err := NewRedisClient()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := NewDB()
	if err != nil {
		return nil, nil, err
	}
	dao, cleanup2, err := New(redisClient, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return dao, func() {
		cleanup2()
		cleanup()
	}, nil
}
