// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"angrymiao-go/app/infra/canal/internal/dao"
	"angrymiao-go/app/infra/canal/internal/server/http"
	"angrymiao-go/app/infra/canal/internal/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	db, cleanup, err := dao.NewDB()
	if err != nil {
		return nil, nil, err
	}
	daoDao, err := dao.New(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	canal := service.NewCanal(daoDao)
	engine, err := http.New(canal)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app, cleanup2, err := NewApp(canal, engine)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
