# uat dapper-service
servers = ["127.0.0.1:6190"]

[log]
dir = "/data/log/dapper-agent"

[queue]
cache_dir = "/data/log/dapper-collect/data"

[udp_collect]
#addr = "unixgram:///var/run/dapper-collect/dapper-collect.sock"
addr = "udp://127.0.0.1:11400"